parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/DTO/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Action\:
        resource: '../src/Action/*Action.php'
        lazy: true
        tags:
            - { name: 'app.action' }